### PR TITLE
Using gallery view

### PR DESCRIPTION
**Pull request by Hooloovoo**
The previous version did not work for me at all, potentially because the site has changed quite a bit since this was last worked on. I made some changes to make it login, then rewrote most of the logic so that, instead of working down the continuous timeline capturing images, it:

1. navigates to the Gallery page
2. scrolls down the page, capturing image numbers
3. uses the API to download full-quality versions of each image

This has the advantages of (working,) more easily finding a complete set of images (from the Gallery view) and pulling down better quality (the timeline uses size "medium" by default instead of "full"). It has the disadvantage of not currently supporting videos, as these are not in the Gallery view.

### CODE REVIEW

**Comment by Hooloovoo** [comment]
Ah, I see in Issue 4 that your original is still working for you @robintw, so you may be less keen on taking this in, given it has some pros and cons (mainly missing videos) -- I thought it was broken for everyone.

**Comment by robintw** [comment]
Hi - thanks for contributing!

Yes, the original is still working for me - I really don't understand why it works fine for me, but not for anyone else.

I'm on holiday at the moment, so can't delve into this too deeply right now - but I've just tested out your version, and it seems to stop after only going down a couple of 'screensful' on the gallery view, and therefore only downloads some of my photos. I'm not quite sure why it's doing this, as a glance at the logic in the code suggests it should be working. I'll try and have a go at debugging it when I have chance.

**Comment by Hooloovoo** [comment]
I have a couple of "time.sleep"s in there that are needed to stop it crashing and my guess would be that it depends on connection speed (I have a ToDo in there to replace them with implicit waits).

When you have a chance, can you please try increasing the time.sleep in line 108 to 3 or 4 and see if it then works?

**Comment by Hooloovoo** [comment]
Thanks for the quick response. 

You may like to try increasing the time.sleep in line 108. It is not doing anything intelligent, but I need that in there to stop it crashing. It wouldn't surprise me if it needed more time on a slower connection to gather all the pictures (and if they aren't loaded when it is doing the driver.find_elements, maybe it doesn't think there are any new photos on the page)?

Perhaps worth trying when you are back and have a minute anyway.

**Comment by Hooloovoo** [comment]
I am going to close this pull request, as I see:
https://github.com/Kloopy/ParentZoneDownloader
has managed to avoid Selenium and use the underlying API directly. When I have a minute I will try to rewrite using that approach, as it would be far better and then I can ensure that there is no functionality loss for anyone where your existing approach is still working for them (specifically adding in Video support) before I request a merge.

**Pull request closed without merging**
