### PR TITLE
A fix for the dropdown selector

### PR DESCRIPTION
**Pull request by timabell**
plus some other setup bits that were useful for me

It'll still be fragile if they add another dropdown, but it works for now

### CODE REVIEW

**Comment by timabell** [comment]
Thanks for creating this, don't know why they don't offer a download button.

**Comment by robintw** [comment]
Thanks for the contribution.

Interestingly, the previous (unaltered) version still works fine for me. Can you provide more information about what problem you were trying to solve with this PR?

**Comment by timabell** [comment]
```
Traceback (most recent call last):
  File "./download_parentzone_photos.py", line 91, in <module>
    get_parentzone_photos()
  File "/home/tim/.asdf/installs/python/3.8.5/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/tim/.asdf/installs/python/3.8.5/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/tim/.asdf/installs/python/3.8.5/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tim/.asdf/installs/python/3.8.5/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./download_parentzone_photos.py", line 42, in get_parentzone_photos
    dropdown = Select(driver.find_element_by_xpath('//*[@id="filter"]/div[2]/div[4]/div/div[1]/select'))
  File "/home/tim/.asdf/installs/python/3.8.5/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/tim/.asdf/installs/python/3.8.5/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/tim/.asdf/installs/python/3.8.5/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/tim/.asdf/installs/python/3.8.5/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="filter"]/div[2]/div[4]/div/div[1]/select"}
  (Session info: chrome=84.0.4147.105)
```

**Comment by robintw** [comment]
Hmm, that's interesting. Perhaps ParentZone are doing some A/B testing or something, that results in you getting a different interface from me.

Anyway, the new code in your PR seems to work for me too, so I'll merge it now.

**Pull request merged**
